### ISSUE TITLE
suggestion: use the withr package

### ISSUE THREAD

**Issue by maelle** [oggioniale/ReLTER#108]
For instance

https://github.com/ropensci/ReLTER/blob/85ee714bce5895d97a338d8897d20ea2dbca531f/tests/testthat/test-get_site_ODS.R#L7

would be

```r
withr::local_envvar("LOCAL_DEIMS" = FALSE)
```

and 

https://github.com/ropensci/ReLTER/blob/85ee714bce5895d97a338d8897d20ea2dbca531f/tests/testthat/test-get_site_ODS.R#L17

would be deleted as the withr change is only for within the test.

**Comment by oggioniale** [comment]
You propose to add 
```r
withr::local_envvar("LOCAL_DEIMS" = FALSE)
```
for all tests where we use `"LOCAL_DEIMS"=...`?

**Comment by oggioniale** [comment]
I implemented your suggestion with this [commit](https://github.com/ropensci/ReLTER/commit/a3ccc7fd7993d76f6b84ba162eb7731542960080)

**Comment by maelle** [comment]
@oggioniale cool! you need to list withr under Suggests in DESCRIPTION.
