### ISSUE TITLE
Warning in getSiteBoundaries

### ISSUE THREAD

**Issue by micha-silver** [oggioniale/ReLTER#17]
Some sites throw a warning in the `getSiteBoundaries()` function:

```
deimsid = "https://deims.org/79d6c1df-570f-455f-a929-6cfe5c4ca1e9"   # Zone Atelier Alps
 b <- getSiteBoundaries(deimsid=deimsid) 
 Imported 1 records. Simplifying...
Warning messages:
1: In biomeColor$geoBonBiome == geoBonBiome :
  longer object length is not a multiple of shorter object length
2: In biomeColor$geoBonBiome == geoBonBiome :
  longer object length is not a multiple of shorter object length
```

I think this is due to multiple colors in the site attributes:
```
geoBonBiome <- jsonlite::fromJSON(
    paste0(
      "https://deims.org/",
      "api/sites/",
      sub("^.+/", "", deimsid)
    )
  )$attributes$environmentalCharacteristics$geoBonBiome

geoBonBiome
[1] "Fresh water lakes" "Terrestrial" 
 
```

Two suggestions:

1. Can we define `biomeColor$geoBonBiome` Capitalized and with spaces as in DEIMS, so that the strings match?
2. Perhaps add a [] subset in the color definition lines 52, 53:

```
  color <- biomeColor$fill[biomeColor$geoBonBiome == geoBonBiome[1]]
  colorBorder <- biomeColor$border[biomeColor$geoBonBiome == geoBonBiome[1]]
```

**Comment by oggioniale** [comment]
@micha-silver I solved the warning following your suggestions (both).
But we need to thinking how colorate the shape accordingly with all the geoBonBiome declared. Otherwise we can forgot this aspect.
