### ISSUE TITLE
New get_site_MODIS function

### ISSUE THREAD

**Issue by micha-silver** [oggioniale/ReLTER#34]
I'd like to suggest a new function to acquire MODIS layers (relying on the MODIStsp packatge) and clip DEIMS site boundaries. Can I do a PR to the dev branch for this?

**Comment by oggioniale** [comment]
@micha-silver today at 14:30 I have an appointment with my colleagues in order to solve the issues already open for close the submission of ROpenSci. I'm confidential that we can close in few hours. I would prefer to close this one before putting more meat on the fire.

**Comment by micha-silver** [comment]
Right, fine
