### ISSUE TITLE
Possible enhancements to get_site_speciesOcc

### ISSUE THREAD

**Issue by micha-silver** [oggioniale/ReLTER#43]
This new function is a nice addition!
Two comments:

- Can we return an `sf` object instead of a list? (provided the species occurrences have longitude/latitude). This is to keep the spatial character of `ReLTER`.  Throughout the package we have a "show_map" flag  for demonstration of the various functions capabilities. But in a research context, I think users will always want to do further analysis - spatial relationships, etc. So returning a spatial object would make sense here.
- Maybe this is "nitpicking" but could the function name be more understandable: i.e. get_site_speciesOccurances ??

**Comment by oggioniale** [comment]
https://github.com/oggioniale/ReLTER/commit/7b4ec67ff16e48e8f00c96e6ec11dc873f116369#commitcomment-65690851
